spring.application.name=app

# Database connection
spring.datasource.url=jdbc:postgresql://localhost:5432/realtimeview
spring.datasource.username=flax
spring.datasource.password=postgres

# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Suppress Warning
spring.jpa.open-in-view=false

# Alpha Vantage
alphavantage.api.key=B8GUXY3M86FWUZSJ